Maximum comparison: report step1 das query to align steps for all workflows, report summary as html table (#2335)
* Create table of maxmem profile results in html format

* Use full workflow name for json file

* Black formatting

* Wait for previous batch set of jobs to complete:

* Revert changes to run-ib-pr-matrix.sh

* Add notice when maxmem-profile comparison starts

* Update run-pr-comparisons

* move maxmem comparison on top and use wf num for json files

* search and use maxmem_profile_ directly

* typo in run comparison

---------

Co-authored-by: Malik Shahzad Muzaffar <shahzad.malik.muzaffar@cern.ch>

diff --git a/pr_testing/run-pr-comparisons b/pr_testing/run-pr-comparisons
--- a/pr_testing/run-pr-comparisons
+++ b/pr_testing/run-pr-comparisons
@@ -289,6 +289,30 @@ popd
 
 set +x
 # --------------------------------------------------------------------------
+# maxmem-profile comparison
+# --------------------------------------------------------------------------
+echo "Started maxmem-profile comparison at `date`"
+OUTPUT_DIR=$WORKSPACE/results/maxmem-comparison
+#create the output dir
+mkdir -p $OUTPUT_DIR
+for maxmem in $(find $WORKSPACE/data/PR-${PR_NUM} -follow -name 'maxmem_profile_*.txt' -type f | sed "s|$WORKSPACE/data/PR-${PR_NUM}/||") ; do
+  echo "Maxmem Profile> Working on ${maxmem}"
+  if [ ! -e "$WORKSPACE/data/$COMPARISON_RELEASE/${maxmem}" ] ; then
+    echo "ERROR: Missing Ref MaxMemory file: $COMPARISON_RELEASE/${maxmem}"
+    continue
+  fi
+  WF_NUMBER=$(echo ${maxmem} | sed 's|_.*||')
+  $CMS_BOT_DIR/comparisons/compare-maxmem.py $WORKSPACE/data/PR-${PR_NUM}/${maxmem} \
+    $WORKSPACE/data/$COMPARISON_RELEASE/${maxmem} > $OUTPUT_DIR/${WF_NUMBER}.json 2> $OUTPUT_DIR/${WF_NUMBER}.err || true
+done
+$CMS_BOT_DIR/comparisons/compare-maxmem-summary.py -i $OUTPUT_DIR -f '*.json' -F html -o $OUTPUT_DIR/index.html -u $JENKINS_ARTIFACTS_URL/$PR_BASELINE_DIR || true
+if grep "exceeds threshold" $OUTPUT_DIR/*.err 2>/dev/null; then
+  echo "MAXMEM_COMPARISON${TEST_FLAVOR_STR};OK,max memory used ${UC_TEST_FLAVOR} comparison,See results,/SDT/jenkins-artifacts/$COMP_UPLOAD_DIR/maxmem-comparison" >> ${RESULTS_FILE}
+else
+  echo "MAXMEM_COMPARISON${TEST_FLAVOR_STR};OK,max memory used ${UC_TEST_FLAVOR} comparison,See results,/SDT/jenkins-artifacts/$COMP_UPLOAD_DIR/maxmem-comparison" >> ${RESULTS_FILE}
+fi
+
+# --------------------------------------------------------------------------
 # JR-Comparison
 # --------------------------------------------------------------------------
 #This is used mainly for testing. In jenkins the 3 forms of comparisons are always run. But if you are testing you can control
@@ -388,25 +412,6 @@ fi
 echo "Jobs: $(jobs -p | wc -l)"
 jobs
 
-# --------------------------------------------------------------------------
-# maxmem-profile comparison
-# --------------------------------------------------------------------------
-OUTPUT_DIR=$WORKSPACE/results/maxmem-comparison
-#create the output dir
-mkdir -p $OUTPUT_DIR
-for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do
-  WF_DIR=`echo $WF | cut -d "/" -f1`
-  WF_NUMBER=`echo $WF | cut -d'_' -f1`
-  WF_FILE=$(basename $WF)
-  if [ -f $WORKSPACE/data/$COMPARISON_RELEASE/$WF_DIR/maxmem_profile_${WF_NUMBER}.txt ] ; then
-    $CMS_BOT_DIR/comparisons/compare-maxmem.py $WORKSPACE/data/PR-${PR_NUM}/$WF_DIR/maxmem_profile_${WF_NUMBER}.txt $WORKSPACE/data/$COMPARISON_RELEASE/$WF_DIR/maxmem_profile_${WF_NUMBER}.txt > $OUTPUT_DIR/${WF_NUMBER}.txt 2> $OUTPUT_DIR/${WF_NUMBER}.err || true
-  fi
-done
-if grep "exceeds threshold" $OUTPUT_DIR/*.err 2>/dev/null; then
-    echo "MAXMEM_COMPARISON${TEST_FLAVOR_STR};OK,max memory used ${UC_TEST_FLAVOR} comparison,See results,/SDT/jenkins-artifacts/$COMP_UPLOAD_DIR/maxmem-comparison" >> ${RESULTS_FILE}
-else
-    echo "MAXMEM_COMPARISON${TEST_FLAVOR_STR};OK,max memory used ${UC_TEST_FLAVOR} comparison,See results,/SDT/jenkins-artifacts/$COMP_UPLOAD_DIR/maxmem-comparison" >> ${RESULTS_FILE}
-fi
 # ----------------------------------------------------------------------------
 # Alternative Comparison
 # ----------------------------------------------------------------------------
