merge validateJR.sh in to run-pr-comparison; run more jobs in parallel

diff --git a/pr_testing/run-pr-comparisons b/pr_testing/run-pr-comparisons
--- a/pr_testing/run-pr-comparisons
+++ b/pr_testing/run-pr-comparisons
@@ -5,19 +5,12 @@ function filter_failed_comparison(){
     if [ $(grep 'Skipped:\|Null:\|Fail:' $1/index.html | wc -l) -gt 0 ] ; then
       echo "Keeping workflow: $1"
     else
-      touch $1/.deleteme 
+      touch $1/.deleteme
     fi
   fi
 }
 
 function wait_dqm_comp(){
-  echo "DQM_PID: ${DQM_PID}"
-  if [ "${DQM_PID}" != "" ] ; then
-    ps -p "$DQM_PID" -o pid,cmd || true
-    if [ $(ps -p "$DQM_PID" -o cmd | grep '/compareDQMOutput.py ' | wc -l) -gt 0 ] ; then
-      pgrep -P $DQM_PID -f || true
-    fi
-  fi
   while true ; do
     djobs=0
     if [ "${DQM_PID}" != "" ] ; then
@@ -27,7 +20,7 @@ function wait_dqm_comp(){
       [ $djobs -gt 0 ] || DQM_PID=""
     fi
     let djobs=${djobs}+$(jobs -p | wc -l) || true
-    if [ $djobs -lt ${NUM_PROC} ] ; then break ; fi
+    if [ $djobs -le ${NUM_PROC} ] ; then break ; fi
     sleep $1
   done
 }
@@ -201,7 +194,85 @@ popd
 
 [ "${PID_WAIT}" = "" ] || wait ${PID_WAIT}
 PID_WAIT=""
+
 set +x
+# --------------------------------------------------------------------------
+# JR-Comparison
+# --------------------------------------------------------------------------
+#This is used mainly for testing. In jenkins the 3 forms of comparisons are always run. But if you are testing you can control
+#which comparison is run.
+if [ "X$RUN_JR_COMP" = Xtrue ]; then
+  mark_commit_status_all_prs "${GH_COMP_CONTEXT}" 'pending' -u "${BUILD_URL}" -d "Running JR comparion" || true
+  pushd $JR_COMP_DIR
+    echo "Start JR comparison at `date`"
+    baseA="$WORKSPACE/data/PR-$PR_NUM"
+    baseB="$WORKSPACE/data/${COMPARISON_RELEASE}"
+    diffN="OldVSNew"
+    dL=""
+    grep root $CMS_BOT_DIR/comparisons/matrix_RE.txt | grep -v "#" > filtered_matrix_RE.txt
+    #check from map patterns to the local
+    while read -r dsN fNP procN comm; do
+      dP=$(echo "${fNP}" | sed -e 's?/[^/]*.root??g'); d=$(echo ${baseA}/$dP | cut -d" " -f1)
+      [ -d "${d}" ] && dL="$dL ${d}/"
+    done <filtered_matrix_RE.txt
+    #check the found mapped list with all that we have
+    ls -d ${baseA}/[1-9]* | while read -r d; do
+      echo "${dL}" | grep  " $d/" >& /dev/null || echo $d >> missing_map.txt
+    done
+    PID_WAIT=""
+    while read -r dsN fNP procN comm; do
+      #fNP can be a pattern: path-expand it first
+      fN=$(echo ${baseA}/${fNP} | cut -d" " -f1 | sed -e "s?^${baseA}/??g")
+      #process regular files first; need files both in baseA and baseB
+      if [ -f "${baseA}/${fN}" -a -f "${baseB}/${fN}" ]; then
+        wait_dqm_comp 2
+        (LD_LIBRARY_PATH=$WORKSPACE/validateJR_lib:${LD_LIBRARY_PATH} $CMS_BOT_DIR/comparisons/validateJR.sh "all_${diffN}_${dsN}" "$WORKSPACE/data/PR-$PR_NUM" "$WORKSPACE/data/$COMPARISON_RELEASE" "${fN}" "${procN}" || true) &
+        PID_WAIT="$!"
+      fi
+      #process miniAOD files now
+      fNBase=$(echo ${fN} | sed -e 's/.root$//g')
+      mFN="${fNBase}_inMINIAOD.root"
+      if [ ! -f "${baseA}/${mFN}" ]; then
+        mFN="${fNBase}_inMINIAODSIM.root"
+      fi
+      #need files both in baseA and baseB
+      if [ -f "${baseA}/${mFN}" -a -f "${baseB}/${mFN}" ]; then
+        wait_dqm_comp 2
+        (LD_LIBRARY_PATH=$WORKSPACE/validateJR_lib:${LD_LIBRARY_PATH} $CMS_BOT_DIR/comparisons/validateJR.sh "all_mini_${diffN}_${dsN}" "$WORKSPACE/data/PR-$PR_NUM" "$WORKSPACE/data/$COMPARISON_RELEASE" "${mFN}" "${procN}" || true) &
+        PID_WAIT="$!"
+      fi
+    done <filtered_matrix_RE.txt
+  popd
+fi
+echo "Jobs: $(jobs -p | wc -l)"
+jobs
+
+#-----------------------------------
+# Comparisons of edm::TriggerResults
+#-----------------------------------
+RUN_TR_COMP=true # placeholder: to be configured upstream?
+if [ "X$RUN_TR_COMP" = Xtrue ]; then
+  echo "[`date`] Starting comparisons of edm::TriggerResults"
+  mkdir -p ${WORKSPACE}/upload/triggerResults
+  for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do
+    wait_dqm_comp 0.5
+    WF_DIR=`echo ${WF} | cut -d "/" -f1`
+    echo "Running: edm::TriggerResults ${WF_DIR}"
+    (${CMS_BOT_DIR}/compareTriggerResults -r ${WORKSPACE}/data/${COMPARISON_RELEASE} -t ${WORKSPACE}/data/PR-${PR_NUM} \
+      -f "*/${WF_DIR}/step*.root" -o ${WORKSPACE}/upload/triggerResults > ${WORKSPACE}/upload/triggerResults/${WF_DIR}.log 2>&1 || true) &
+  done
+fi
+echo "Jobs: $(jobs -p | wc -l)"
+jobs
+
+#Wait for JR comparison jobs
+if [ "X$RUN_JR_COMP" = Xtrue ]; then
+  [ "${PID_WAIT}" = "" ] || wait ${PID_WAIT}
+  echo "Finished with JR comparison at `date`:"
+  rm -rf $WORKSPACE/validateJR_lib
+  (${CMSBOT_PYTHON_CMD} $CMS_BOT_DIR/logRootQA.py $WORKSPACE/data/${COMPARISON_RELEASE} $WORKSPACE/data/PR-${PR_NUM} ${JR_COMP_DIR} $WORKSPACE/results/default-comparison JR >${JR_COMP_DIR}/logRootQA-JR.log 2>&1 || true) &
+fi
+
 # --------------------------------------------------------------------------
 # Default Comparison
 # --------------------------------------------------------------------------
@@ -210,13 +281,12 @@ if [ "X$RUN_DEFAULT_COMP" = Xtrue ]; then
   echo "Started with default comparison at `date`"
   
   RELMON_COMP_DIR=$WORKSPACE/results/default-comparison
+  RELMON_COMP_PARAMS_FILE=$RELMON_COMP_DIR/RelMonComparisonParams.txt
   mkdir $RELMON_COMP_DIR
 
   if [ "X$RUN_JR_COMP" = Xtrue ]; then
-    RELMON_COMP_PARAMS_FILE=$RELMON_COMP_DIR/RelMonComparisonParams.txt
-    $CMS_BOT_DIR/comparisons/analyzeFWComparison.py $JR_COMP_DIR $RELMON_COMP_PARAMS_FILE -R >> $RELMON_COMP_DIR/RelMonAssignedParameters.log 2>&1
+    $CMS_BOT_DIR/comparisons/analyzeFWComparison.py $JR_COMP_DIR $RELMON_COMP_PARAMS_FILE -R > $RELMON_COMP_DIR/RelMonAssignedParameters.log 2>&1
   fi
-  PID_WAIT=""
   for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do 
     WF_FILE=$(basename $WF)
     WF_DIR=`echo $WF | cut -d "/" -f1`
@@ -228,7 +298,7 @@ if [ "X$RUN_DEFAULT_COMP" = Xtrue ]; then
 
     # If there is a file assigning custom thresholds from the results of the FWlite (JR) comparison, use it
     if [ "X$RUN_JR_COMP" = Xtrue ]; then
-      eval $( cat $RELMON_COMP_PARAMS_FILE | grep "FOR_WF=$WF_NUMBER;" )
+      eval $(cat $RELMON_COMP_PARAMS_FILE | grep "FOR_WF=$WF_NUMBER;" )
       echo "TH=$TH"
       if [ "${TH}" = "" ] ; then TH="0.999999999999"; echo "Overriding TH=$TH" ; fi
       TH_PARAM="-t $TH "
@@ -243,80 +313,21 @@ if [ "X$RUN_DEFAULT_COMP" = Xtrue ]; then
     echo "cp $OUTPUT_DIR/RelMonSummary.html $OUTPUT_DIR/index.html || true" >> $WORKSPACE/results/default-comparison/command-$WF_NUMBER
     echo 'exit $ERR' >> $WORKSPACE/results/default-comparison/command-$WF_NUMBER
     chmod 755 $WORKSPACE/results/default-comparison/command-$WF_NUMBER
-    wait_dqm_comp 1
+    wait_dqm_comp 0.5
     echo "Running $WORKSPACE/results/default-comparison/command-$WF_NUMBER"
     ($WORKSPACE/results/default-comparison/command-$WF_NUMBER > ${OUTPUT_DIR}/cmd.log 2>&1 || touch $WORKSPACE/results/default-comparison/error-$WF_NUMBER) &
-    PID_WAIT="$! ${PID_WAIT}"
-    echo "PIDS: ${PID_WAIT}"
   done
-  echo "Jobs: $(jobs -p | wc -l)"
 fi
-
-#-----------------------------------
-# Comparisons of edm::TriggerResults
-#-----------------------------------
-RUN_TR_COMP=true # placeholder: to be configured upstream?
-if [ "X$RUN_TR_COMP" = Xtrue ]; then
-  echo "[`date`] Starting comparisons of edm::TriggerResults"
-  mkdir -p ${WORKSPACE}/upload/triggerResults
-  PID_WAIT=""
-  for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do
-    wait_dqm_comp 1
-    WF_DIR=`echo ${WF} | cut -d "/" -f1`
-    echo "Running: edm::TriggerResults ${WF_DIR}"
-    (${CMS_BOT_DIR}/compareTriggerResults -r ${WORKSPACE}/data/${COMPARISON_RELEASE} -t ${WORKSPACE}/data/PR-${PR_NUM} \
-      -f "*/${WF_DIR}/step*.root" -o ${WORKSPACE}/upload/triggerResults > ${WORKSPACE}/upload/triggerResults/${WF_DIR}.log 2>&1 || true) &
-    PID_WAIT="$! ${PID_WAIT}"
-    echo "PIDS: ${PID_WAIT}"
-  done
-  echo "Jobs: $(jobs -p | wc -l)"
-fi
-
-wait || true
-if $DQM_COMPARISON_TEST ; then
-  echo "DQM_BIN_BY_BIN_COMPARISON${TEST_FLAVOR_STR};OK,DQM bin by bin ${UC_TEST_FLAVOR} comparison,See results,/SDT/jenkins-artifacts/${COMP_UPLOAD_DIR}/dqm-histo-comparison-summary.html" >> ${RESULTS_FILE}
-fi
-if [ "X$RUN_DEFAULT_COMP" = Xtrue ]; then
-  rm -f $WORKSPACE/results/default-comparison/cmdlog-*
-  echo "Finished with default comparison at `date`"
-  if [ "X${FILTER_FAILED_COMPARISON}" = "Xtrue" ] ; then
-    for f in $WORKSPACE/results/default-comparison/* ; do
-      filter_failed_comparison "$f"
-    done
-  fi
-fi
-if [ "X$RUN_TR_COMP" = Xtrue ]; then
-  echo "[`date`] Done comparisons of edm::TriggerResults"
-  ${CMS_BOT_DIR}/compareTriggerResultsSummary -i ${WORKSPACE}/upload/triggerResults -f "*/*.json" -o ${WORKSPACE}/upload/triggerResults/index.html -F html > ${WORKSPACE}/upload/triggerResults.log 2>&1 || true
-  echo "[`date`] Summary of TriggerResults comparisons saved in ${WORKSPACE}/upload/triggerResults.log"
-  echo "HLT_TRIGGER_COMPARISON${TEST_FLAVOR_STR};OK,HLT Trigger ${UC_TEST_FLAVOR} comparison,See results,/SDT/jenkins-artifacts/${COMP_UPLOAD_DIR}/triggerResults/" >> ${RESULTS_FILE}
-fi
-
-# --------------------------------------------------------------------------
-# JR-Comparison
-# --------------------------------------------------------------------------
-#This is used mainly for testing. In jenkins the 3 forms of comparisons are always run. But if you are testing you can control
-#which comparison is run.
-if [ "X$RUN_JR_COMP" = Xtrue ]; then
-  mark_commit_status_all_prs "${GH_COMP_CONTEXT}" 'pending' -u "${BUILD_URL}" -d "Running JR comparion" || true
-  pushd $JR_COMP_DIR
-    echo "Start JR comparison at `date`"
-    echo  "$CMS_BOT_DIR/comparisons/validateJR.sh $WORKSPACE/data/PR-$PR_NUM $WORKSPACE/data/$COMPARISON_RELEASE OldVSNew $CMS_BOT_DIR/comparisons/matrix_RE.txt >> $JR_COMP_DIR/validateJR.log 2>&1" > $JR_COMP_DIR/command
-    (LD_LIBRARY_PATH=$WORKSPACE/validateJR_lib:${LD_LIBRARY_PATH} $CMS_BOT_DIR/comparisons/validateJR.sh $WORKSPACE/data/PR-$PR_NUM $WORKSPACE/data/$COMPARISON_RELEASE OldVSNew $CMS_BOT_DIR/comparisons/matrix_RE.txt >> $JR_COMP_DIR/validateJR.log 2>&1) || true
-    echo "Finished with JR comparison at `date`:"
-  popd
-  rm -rf $WORKSPACE/validateJR_lib
-  (${CMSBOT_PYTHON_CMD} $CMS_BOT_DIR/logRootQA.py $WORKSPACE/data/${COMPARISON_RELEASE} $WORKSPACE/data/PR-${PR_NUM} ${JR_COMP_DIR} $WORKSPACE/results/default-comparison JR || true) >${JR_COMP_DIR}/logRootQA-JR.log 2>&1 &
-fi
+echo "Jobs: $(jobs -p | wc -l)"
+jobs
 
 # ----------------------------------------------------------------------------
 # Alternative Comparison
 # ----------------------------------------------------------------------------
-
 if [ "X$RUN_ALT_COMP" = Xtrue ]; then
   mark_commit_status_all_prs "${GH_COMP_CONTEXT}" 'pending' -u "${BUILD_URL}" -d "Running alternative comparison" || true
   echo "Started with alternative comparison at `date`"
-  
+
   ALT_COMP_DIR=$WORKSPACE/results/alternative-comparison
   mkdir -p $ALT_COMP_DIR
   DQM_COMP_PARAMS_FILE=$ALT_COMP_DIR/comparisonParams.txt
@@ -324,14 +335,14 @@ if [ "X$RUN_ALT_COMP" = Xtrue ]; then
   if [ "X$RUN_JR_COMP" = Xtrue ]; then
     $CMS_BOT_DIR/comparisons/analyzeFWComparison.py $JR_COMP_DIR $DQM_COMP_PARAMS_FILE >> $ALT_COMP_DIR/assignedParameters.log 2>&1
   fi
-  for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do 
+  for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do
 
     WF_FILE=$(basename $WF)
     WF_DIR=`echo $WF | cut -d "/" -f1`
     WF_NUMBER=`echo $WF | cut -d'_' -f1`
     BASE_FILE=$WORKSPACE/results/files/$WF_DIR/$COMPARISON_RELEASE-$WF_FILE
     COMP_FILE=$WORKSPACE/results/files/$WF_DIR/$PR_NUM-$WF_FILE
-  
+
     mkdir -p $ALT_COMP_DIR/$WF_NUMBER
     eval $( cat $DQM_COMP_PARAMS_FILE | grep "FOR_WF=$WF_NUMBER;" )
     if [ "${MOD}" = "" ] ; then MOD=0; echo "Overriding MOD=$MOD";  fi
@@ -349,16 +360,30 @@ if [ "X$RUN_ALT_COMP" = Xtrue ]; then
     echo 'exit $ERR' >> $ALT_COMP_DIR/command-$WF_NUMBER
 
     chmod 755 $ALT_COMP_DIR/command-$WF_NUMBER
-    while [ $(jobs -p | wc -l) -ge ${NUM_PROC} ] ; do sleep 0.1 ; done
+    wait_dqm_comp 0.2
     echo "Running $ALT_COMP_DIR/command-$WF_NUMBER"
     (LD_LIBRARY_PATH=$WORKSPACE/validateALT_lib:${LD_LIBRARY_PATH} $ALT_COMP_DIR/command-$WF_NUMBER > $ALT_COMP_DIR/runDQMComp-$WF_NUMBER.log 2>&1 || touch $ALT_COMP_DIR/error-$WF_NUMBER) &
   done
-  echo "Jobs: $(jobs -p | wc -l)"
-  wait
-  rm -rf $WORKSPACE/validateALT_lib
-  echo "Finished with alternative comparison at `date`"
 fi
-wait || true
+
+echo "Jobs: $(jobs -p | wc -l)"
+jobs
+wait
+rm -rf $WORKSPACE/validateALT_lib
+[ "X$RUN_ALT_COMP" = Xtrue ] && echo "Finished with alternative comparison at `date`"
+if [ "X$RUN_DEFAULT_COMP" = Xtrue ]; then
+  echo "Finished with default comparison at `date`"
+  rm -f $WORKSPACE/results/default-comparison/cmdlog-*
+  if [ "X${FILTER_FAILED_COMPARISON}" = "Xtrue" ] ; then
+    for f in $WORKSPACE/results/default-comparison/* ; do
+      filter_failed_comparison "$f"
+    done
+  fi
+fi
+if $DQM_COMPARISON_TEST ; then
+  echo "DQM_BIN_BY_BIN_COMPARISON${TEST_FLAVOR_STR};OK,DQM bin by bin ${UC_TEST_FLAVOR} comparison,See results,/SDT/jenkins-artifacts/${COMP_UPLOAD_DIR}/dqm-histo-comparison-summary.html" >> ${RESULTS_FILE}
+fi
+
 #----------------------------------
 # Comparison summary
 #----------------------------------
@@ -400,15 +425,16 @@ if [ "X$RUN_JR_COMP" = Xtrue ]; then
 fi
 
 if [ "X$RUN_TR_COMP" = Xtrue ]; then
+  echo "[`date`] Done comparisons of edm::TriggerResults"
+  ${CMS_BOT_DIR}/compareTriggerResultsSummary -i ${WORKSPACE}/upload/triggerResults -f "*/*.json" -o ${WORKSPACE}/upload/triggerResults/index.html -F html > ${WORKSPACE}/upload/triggerResults.log 2>&1 || true
+  echo "[`date`] Summary of TriggerResults comparisons saved in ${WORKSPACE}/upload/triggerResults.log"
+  echo "HLT_TRIGGER_COMPARISON${TEST_FLAVOR_STR};OK,HLT Trigger ${UC_TEST_FLAVOR} comparison,See results,/SDT/jenkins-artifacts/${COMP_UPLOAD_DIR}/triggerResults/" >> ${RESULTS_FILE}
   if [ -f ${JR_COMP_DIR}/qaResultsSummary.log ]; then
     grep -a SUMMARY ${WORKSPACE}/upload/triggerResults.log | cut -d' ' -f2-100 >> ${JR_COMP_DIR}/qaResultsSummary.log 2>&1 || true
     sed -i "s|TriggerResults|[TriggerResults](${JENKINS_ARTIFACTS_URL}/${COMP_UPLOAD_DIR}/triggerResults)|g" ${JR_COMP_DIR}/qaResultsSummary.log
     echo "[`date`] One-line Summary of TriggerResults comparisons appended to ${JR_COMP_DIR}/qaResultsSummary.log"
   fi
 fi
-
-set -x
-wait || true
 
 cd $WORKSPACE
 mkdir -p upload/alternative-comparisons
@@ -451,6 +477,7 @@ if [ -e results/files ] ; then
     ln -sf $SRC_FILE upload/files/$file
   done
 fi
+set -x
 
 mkdir -p $WORKSPACE/testsResults
 sed -i "s/^COMPARISON${TEST_FLAVOR_STR};RUNNING,/COMPARISON${TEST_FLAVOR_STR};$BUILD_NUMBER,/g" ${RESULTS_FILE}
