use proper command-line options for auto-update-git-branches scripts

diff --git a/auto-update-git-branches b/auto-update-git-branches
--- a/auto-update-git-branches
+++ b/auto-update-git-branches
@@ -1,21 +1,44 @@
 #!/bin/sh -ex
 
-REPO_NAME=$1
-if [ "X$REPO_NAME" = "X" ] ; then
-  echo "Usage: $0 <cmssw|cmsdist> [<src-branch>] [<comma-seperated-commit-hashes>] [<OVERRIDE_STRATEGY>] [push]"
-  exit 1
-fi
-SRC_BRANCH=$2
-COMMITS=$3
-OVERRIDE_STRATEGY=$4
-PUSH_UPDATES=$5
-DES_BRANCH=$6
+has_arg() {
+  [ "X$1" = "X" ] && echo "Error: Missing command-line arg value for $2" && exit 1
+  return 0
+}
 
-GIT_USER="cms-sw"
-SCRIPT_PATH="`dirname \"$0\"`"
-SCRIPT_PATH="`(cd \"$SCRIPT_PATH\" && pwd)`"
-WORKSPACE="${WORKSPACE-$PWD}"
-HAS_ERRORS=0
+parseargs() {
+  set +x
+  while [ $# -gt 0 ]; do
+    arg=$1; shift
+    case $arg in
+    -* )
+      case $arg in
+      -r | --repository ) REPO_NAME=$1 && has_arg $1 $arg && shift ;;
+      -s | --src-branch  ) SRC_BRANCH=$1 && has_arg $1 $arg && shift  ;;
+      -d | --des-branch ) DES_BRANCH=$1 && has_arg $1 $arg && shift  ;;
+      -c | --commits ) COMMITS="-c $1" && has_arg $1 $arg && shift  ;;
+      -X | --strategy ) OVERRIDE_STRATEGY=$1 && has_arg $1 $arg && shift  ;;
+      -p | --push ) PUSH_UPDATES="-p" ;;
+      -h | --help )
+        echo -e "Usage: $0\n\t-r|--repository <repository>\n\t[-s|--src-branch <branch>]\n\t[-d|--des-branch <branch>]"
+        echo -e"\n\t[-c|--commits <comma-seperated-hashes>]\n\t[-X|--strategy <merge-strategy>]\n\t[-p|--push]\n\t[-h|--help]"
+        exit 0 ;;
+      esac ;;
+    * ) echo "Error: Invalid argument $arg."; exit 1;;
+    esac
+  done
+  for s in REPO_NAME#repository ; do
+    v=$(echo $s | sed 's|#.*||')
+    o=$(echo $s | sed 's|.*#||')
+    eval "vc=$(echo \$$v)"
+    err=0
+    if [ "X$vc" = "X" ] ; then 
+      echo "Error: Missing required command-line option --$o <value>"
+      err=1
+    fi
+    [ $err -eq 0 ] || exit 1
+  done
+  set -x
+}
 
 #Some helper functions
 #Return auto forward port branches.
@@ -29,6 +52,14 @@ function getBranches()
     (export PYTHONPATH=$SCRIPT_PATH; echo -e "from forward_ports_map import GIT_REPO_FWPORTS as p\nif '$1' in p and '$2' in p['$1']:\n  print ' '.join(p['$1']['$2'])" | python)
   fi
 }
+
+GIT_USER="cms-sw"
+SCRIPT_PATH="`dirname \"$0\"`"
+SCRIPT_PATH="`(cd \"$SCRIPT_PATH\" && pwd)`"
+WORKSPACE="${WORKSPACE-$PWD}"
+HAS_ERRORS=0
+
+parseargs $@
 
 #make sure we have a full repo name i.e. git-user/git-repo
 case $REPO_NAME in 
@@ -62,16 +93,17 @@ for src in $SRC_BRANCH; do
   if [ "X$DES_BRANCH" = "X" ] ; then DES_BRANCH=$(getBranches $repo $src) ; fi
   for des in $DES_BRANCH; do
     rm -f $LOG_COMMANDS
-    echo ">git clone https://github.com/cms-sw/cms-bot.git cms-bot" > $LOG_COMMANDS
-    echo ">./cms-bot/`basename $0` $REPO_NAME $src $COMMITS" >> $LOG_COMMANDS
     if [ "X$OVERRIDE_STRATEGY" != "X" ] ; then
       merge_strategy=$OVERRIDE_STRATEGY
     else
       merge_strategy=$(echo $des | grep : | sed 's|^[^:]*:||')
     fi
+    [ "X$merge_strategy" = "X" ] || merge_strategy="-X $merge_strategy"
     des=$(echo $des | sed 's|:.*||')
+    echo ">git clone https://github.com/cms-sw/cms-bot.git cms-bot" > $LOG_COMMANDS
+    echo ">./cms-bot/$(basename $0) -r $REPO_NAME -s $src -d $des $COMMITS $merge_strategy" >> $LOG_COMMANDS
     err=0
-    $SCRIPT_PATH/merge-git-branch "$LOG_COMMANDS" "$COMMITS" "$src" "$des" "$merge_strategy" "$PUSH_UPDATES" || err=1
+    $SCRIPT_PATH/merge-git-branch -l $LOG_COMMANDS -s $src -d $des $COMMITS $merge_strategy $PUSH_UPDATES || err=1
     if [ "X$err" = "X1" ] ; then 
       HAS_ERRORS=1
       if [ ! "X$PUSH_UPDATES" = "X" ] ; then
diff --git a/merge-git-branch b/merge-git-branch
--- a/merge-git-branch
+++ b/merge-git-branch
@@ -1,24 +1,58 @@
 #!/bin/sh -ex
-GIT_DIFF_LOGFILE=$1
-COMMITS_LIST=$2
-SOURCE_BRANCH=$3
-TARGET_BRANCH=$4
-STRATEGY=$5
-PUSH_UPDATES=$6
+
+has_arg() {
+  [ "X$1" = "X" ] && echo "Error: Missing command-line arg value for $2" && exit 1
+  return 0
+}
+
+parseargs() {
+  set +x
+  while [ $# -gt 0 ]; do
+    arg=$1; shift
+    case $arg in
+    -* )
+      case $arg in
+      -l | --log-file ) GIT_DIFF_LOGFILE=$1 && has_arg $1 $arg && shift ;;
+      -s | --src-branch  ) SOURCE_BRANCH=$1 && has_arg $1 $arg && shift  ;;
+      -d | --des-branch ) TARGET_BRANCH=$1 && has_arg $1 $arg && shift  ;;
+      -c | --commits ) COMMITS_LIST=$1 && has_arg $1 $arg && shift  ;;
+      -X | --strategy ) STRATEGY=$1 && has_arg $1 $arg && shift  ;;
+      -p | --push ) PUSH_UPDATES=yes ;;
+      -h | --help )
+        echo -e "Usage: $0\n\t-r|--repository <repository>\n\t[-s|--src-branch <branch>]\n\t[-d|--des-branch <branch>]"
+        echo -e"\n\t[-c|--commits <comma-seperated-hashes>]\n\t[-X|--strategy <merge-strategy>]\n\t[-p|--push]\n\t[-h|--help]"
+        exit 0 ;;
+      esac ;;
+    * ) echo "Error: Invalid argument $arg."; exit 1;;
+    esac
+  done
+  for s in GIT_DIFF_LOGFILE#log-file SOURCE_BRANCH#src-branch TARGET_BRANCH#des-branch ; do
+    v=$(echo $s | sed 's|#.*||')
+    o=$(echo $s | sed 's|.*#||')
+    eval "vc=$(echo \$$v)"
+    err=0
+    if [ "X$vc" = "X" ] ; then 
+      echo "Error: Missing required command-line option --$o <value>"
+      err=1
+    fi
+    [ $err -eq 0 ] || exit 1
+  done
+  set -x
+}
+parseargs $@
+
 #clean up any previous un-commited changes
 git clean -fdx
 #checkout target branch and remove any local changes
 git checkout -q --force $TARGET_BRANCH
 git reset --hard origin/$TARGET_BRANCH
-MERGE_COMMIT_MSG=""
 STRATEGY_OPTS=""
 DEFAULT_MERGE_COMMIT_MSG="Merge $SOURCE_BRANCH into $TARGET_BRANCH."
 #Depending on the commits, use either cherry-pick or merge
 if [ "X$COMMITS_LIST" = "X" ] ; then
   #We do not have the commits to just try to merge source branch in to target
   [ "X$STRATEGY" = "X" ] || STRATEGY_OPTS="-X $STRATEGY"
-  git merge --no-ff $STRATEGY_OPTS origin/$SOURCE_BRANCH || (git diff >> $GIT_DIFF_LOGFILE && exit 1)
-  MERGE_COMMIT_MSG="$DEFAULT_MERGE_COMMIT_MSG"
+  git merge -m "$DEFAULT_MERGE_COMMIT_MSG" --no-ff $STRATEGY_OPTS origin/$SOURCE_BRANCH || (git diff >> $GIT_DIFF_LOGFILE && exit 1)
 else
   #We have the commits list, so do cherry picking by doing the following
   #  1. Create and checkout new dummy branch based on target branch
@@ -31,8 +65,12 @@ else
   #      - merge the new dummy branch in to the target branch
   #      - amend the commit message
   #      - checkout the dummy branch again and repeat step 2
-  DUMMY_BRANCH=$(whoami)-auto-forward-port-dummy-branch  
-  [ "X$STRATEGY" = "X" ] || STRATEGY_OPTS="-X $STRATEGY"
+  DUMMY_BRANCH=$(whoami)-auto-forward-port-dummy-branch
+  if [ ! "X$STRATEGY" = "X" ] ; then
+    if [ ! "X$(git cherry-pick -h 2>&1 | grep 'strategy-option' | tail -1)" = "X" ] ; then
+      STRATEGY_OPTS="-X $STRATEGY"
+    fi
+  fi
   #Delete dummy branch if exists
   git branch -D $DUMMY_BRANCH || true
   #Create and checkout dummy branch
@@ -43,7 +81,7 @@ else
     IsMergeCommit=$([ $(git rev-list --parents -n 1 $c | wc -w) -lt 3 ] || echo YES)
     if [ "X$IsMergeCommit" = X ] ; then
       #Non-merge commit found; cherry pick it
-      if ! git cherry-pick -x $c ; then
+      if ! git cherry-pick -x $STRATEGY_OPTS $c ; then
         git diff >> $GIT_DIFF_LOGFILE
         [ $(git diff --name-only | wc -l) -eq 0 ] || exit 1
       fi
@@ -59,9 +97,7 @@ else
   #If last commit was not a merge commit then we have new commits in dummy branch
   if [ "X$IsMergeCommit" = X ] ; then
     #We have new commits in dummy branch which are not yet merged in to target branch
-    git merge --no-ff $DUMMY_BRANCH
-    #As we do not know the merge commit message so we go back to default message
-    MERGE_COMMIT_MSG="$DEFAULT_MERGE_COMMIT_MSG"
+    git merge -m "$DEFAULT_MERGE_COMMIT_MSG" --no-ff $DUMMY_BRANCH
   fi
   #We are done with cherry-picking, now delete the dummy branch
   git branch -D $DUMMY_BRANCH
@@ -69,7 +105,6 @@ fi
 #We should be on target branch by now
 #Check if local target branch has any changes w.r.t remote target branch
 if [ "X`git diff --name-only HEAD origin/$TARGET_BRANCH | tail -1`" != "X" ]; then
-  [ "X$MERGE_COMMIT_MSG" = "X" ] || git commit --amend -m "$MERGE_COMMIT_MSG"
   #Finaly, push the local target branch to remote target branch
   if [ ! "X$PUSH_UPDATES" = "X" ] ; then
     git push origin $TARGET_BRANCH
