Update jenkins-artifacts

diff --git a/jenkins-artifacts b/jenkins-artifacts
--- a/jenkins-artifacts
+++ b/jenkins-artifacts
@@ -15,6 +15,21 @@ function has_jenkins_artifacts ()
   return 1
 }
 
+function has_jenkins_artifacts1 ()
+{
+  local SRC=$1
+  for i in 1 2 3 4 5 ;  do
+    if [ $(ssh $SSH_OPTS ${ARTIFACTS_MACHINE} "ls -d ${ARTIFACT_BASE_DIR}/${SRC} || echo FAIL" | grep "^FAIL\$" | wc -l) -gt 0 ] ; then
+      sleep 60
+    else
+      echo "JA_STATUS=OK"
+      return 0
+    fi
+  done
+  echo "JA_STATUS=ERROR"
+  return 1
+}
+
 function send_jenkins_artifacts ()
 {
   local SRC=$1
@@ -39,7 +54,7 @@ function get_jenkins_artifacts ()
     */) mkdir -p $DES ; DES="${DES}/";;
     * ) mkdir -p $(dirname $DES) ;;
   esac
-  has_jenkins_artifacts $1 || return 1
+  has_jenkins_artifacts1 $1 || return 1
   for i in 1 2 3 4 5 ;  do
     rsync -az -e "ssh $SSH_OPTS" ${ARTIFACTS_MACHINE}:${ARTIFACT_BASE_DIR}/${SRC} ${DES} && echo "JA_STATUS=OK" && return
     sleep 120
