set req/opt label

diff --git a/pr-schedule-tests b/pr-schedule-tests
--- a/pr-schedule-tests
+++ b/pr-schedule-tests
@@ -7,6 +7,9 @@ cd $WORKSPACE
 
 # The pull request number is $1
 PULL_REQUESTS=$(echo $1 | sed 's/^ *//;s/ *$//')
+PULL_REQUEST="$(echo ${PULL_REQUESTS} | sed 's| .*||')"
+COMMIT=$(${CMS_BOT_DIR}/process-pull-request -c -r $(echo ${PULL_REQUEST} | sed 's/#.*//') $(echo ${PULL_REQUEST} | sed 's/.*#//'))
+echo "${PULL_REQUEST}=${COMMIT}" >> ${WORKSPACE}/prs_commits.txt
 source $CMS_BOT_DIR/pr_testing/_helper_functions.sh
 source $CMS_BOT_DIR/common/github_reports.sh
 
@@ -45,7 +48,7 @@ if [ $(echo $CONFIG_LINE | tr ';' '\n' | grep SCRAM_ARCH= | wc -l) -eq 1 ] ; the
     REQUIRED_TEST=false
     eval $CONFIG_LINE
     OUTPUT_FILE=properties-pr-test-${SCRAM_ARCH}.txt
-    echo PULL_REQUEST="$(echo ${PULL_REQUESTS} | sed 's| .*||')" >> $OUTPUT_FILE
+    echo PULL_REQUEST="${PULL_REQUEST}" >> $OUTPUT_FILE
     echo PULL_REQUESTS=${PULL_REQUESTS} >> $OUTPUT_FILE
     echo ARCHITECTURE=${SCRAM_ARCH} >> $OUTPUT_FILE
     if [ "X$RELEASE_FORMAT" = X ] ; then
@@ -56,6 +59,8 @@ if [ $(echo $CONFIG_LINE | tr ';' '\n' | grep SCRAM_ARCH= | wc -l) -eq 1 ] ; the
       fi
     fi
     if [ "${DOCKER_IMGAGE}" != "" ] ; then  DOCKER_IMG="${DOCKER_IMGAGE}" ; fi
+    PR_COMMIT_STATUS="optional"
+    if ${REQUIRED_TEST} ; then PR_COMMIT_STATUS="required" ; fi
     echo "REQUIRED_TEST=${REQUIRED_TEST}" >> $OUTPUT_FILE
     echo "DRY_RUN=${DRY_RUN}" >> $OUTPUT_FILE
     echo "ENABLE_BOT_TESTS=${ENABLE_BOT_TESTS}" >> $OUTPUT_FILE
@@ -81,7 +86,11 @@ if [ $(echo $CONFIG_LINE | tr ';' '\n' | grep SCRAM_ARCH= | wc -l) -eq 1 ] ; the
     echo "IGNORE_BOT_TESTS=${IGNORE_BOT_TESTS}" >> $OUTPUT_FILE
     echo "EXTRA_CMSSW_PACKAGES=${EXTRA_CMSSW_PACKAGES}" >> $OUTPUT_FILE
     echo "CONFIG_LINE=${CONFIG_LINE}" >> $OUTPUT_FILE
+    CMSSW_QUEUE="${RELEASE_QUEUE}"
+    mark_commit_status_all_prs "${PR_COMMIT_STATUS}" 'pending' -d 'Tests scheduled ${RELEASE_FORMAT}/${SCRAM_ARCH}' -u 'https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/' || true
+    COMMIT_STATUS_CONTEXT="unknown/release"
+    mark_commit_status_all_prs '' 'success' -d 'All OK' || true
 else
-    exit_with_report_failure_main_pr "RELEASE_NOT_FOUND" --pr-job-id ${BUILD_NUMBER}
+    COMMIT_STATUS_CONTEXT="unknown/release"
+    mark_commit_status_all_prs '' 'error' -d 'Unable to find cmssw release to run tests.' || true
 fi
-
