fail if cod-checks failed to merge

diff --git a/run-pr-code-checks b/run-pr-code-checks
--- a/run-pr-code-checks
+++ b/run-pr-code-checks
@@ -58,7 +58,17 @@ pushd $CMSSW_BASE/src
   git repack -a -d ${THRDS}
   git repack -a -d ${THRDS}
   OSIZE=$(du -sk .git/objects/pack | sed 's|\s.*||')
-  git cms-merge-topic -u ${REPO_USER}:${PULL_REQUEST} 2>&1 | tee ${UP_DIR}/cms-checkout-topic.log
+  if ! git cms-merge-topic -u ${REPO_USER}:${PULL_REQUEST} >${UP_DIR}/cms-checkout-topic.log 2>&1 ; then
+    echo '-code-checks' > ${UP_DIR}/code-checks.md
+    echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/code-checks.md
+    echo -e '\nERROR: Unable to merge PR.' >> ${UP_DIR}/code-checks.md
+    echo -e "\nSee log ${UP_URL}/cms-checkout-topic.log" >> ${UP_DIR}/code-checks.md
+    if ! $DRY_RUN ; then
+      send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
+      ${CMS_BOT_DIR}/comment-gh-pr -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/code-checks.md
+    fi
+    exit 0
+  fi
   ERR=false
   for f in $(curl -s -L https://patch-diff.githubusercontent.com/raw/${REPOSITORY}/pull/${PULL_REQUEST}.patch | grep '^diff --git ' | grep '^diff --git ' | sed 's|.* a/||;s|  *b/| |' | tr ' ' '\n' | sort | uniq) ; do
     [ ! -e $f ] || echo "$f" >> ${UP_DIR}/all-changed-files.txt
