add hltPhase2UpgradeIntegrationTests to IB tests

diff --git a/run-hlt-validation b/run-hlt-validation
--- a/run-hlt-validation
+++ b/run-hlt-validation
@@ -39,6 +39,12 @@ cd HLTrigger/Configuration/test/
 ls
 ./runAll.csh IB | tee -a $WORKSPACE/results/runIB.log
 ./examLogs.csh | tee -a $WORKSPACE/results/examLogs.out
+which hltPhase2UpgradeIntegrationTests || true
+if [ $? -eq 0 ]; then
+    hltPhase2UpgradeIntegrationTests | tee -a  $WORKSPACE/results/hltPhase2UpgradeIntegrationTests.log
+else
+    echo "hltPhase2UpgradeIntegrationTests not found, skipping"
+fi
 ls
 cp *.log $WORKSPACE/results
 cp *.out $WORKSPACE/results
