check for BF errors as soon as possible

diff --git a/run-pr-code-checks b/run-pr-code-checks
--- a/run-pr-code-checks
+++ b/run-pr-code-checks
@@ -62,6 +62,21 @@ pushd $CMSSW_BASE/src
   git repack -a -d ${THRDS}
   OSIZE=$(du -sk .git/objects/pack | sed 's|\s.*||')
   git cms-merge-topic -u ${REPO_USER}:${PULL_REQUEST} 2>&1 | tee ${UP_DIR}/cms-checkout-topic.log
+  ERR=false
+  scram build -r echo_CXX > ${UP_DIR}/code-checks.log 2>&1 || ERR=true
+  if $ERR ; then
+    echo '-code-checks' > ${UP_DIR}/code-checks.md
+    echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/code-checks.md
+    echo -e '\nERROR: Build errors found during clang-tidy run.' >> ${UP_DIR}/code-checks.md
+    echo '```' >> ${UP_DIR}/code-checks.md
+    grep 'SCRAM error: ' ${UP_DIR}/code-checks.log | tail -12 >> ${UP_DIR}/code-checks.md || true
+    echo '```' >> ${UP_DIR}/code-checks.md
+    if ! $DRY_RUN ; then
+      send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
+      ${CMS_BOT_DIR}/comment-gh-pr -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/code-checks.md
+    fi
+    exit 0
+  fi
   git repack -d ${THRDS}
   NSIZE=$(du -sk .git/objects/pack | sed 's|\s.*||')
   let DSIZE=${NSIZE}-${OSIZE} || DSIZE=0
@@ -90,8 +105,7 @@ if $CODE_CHECKS ; then
       echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/code-checks.md
       echo -e '\nERROR: Build errors found during clang-tidy run.' >> ${UP_DIR}/code-checks.md
       echo '```' >> ${UP_DIR}/code-checks.md
-      grep -A 3 ': error: \|gmake: \*\*\*' ${UP_DIR}/code-checks.log | tail -12 | sed "s|$CMSSW_BASE/src/||" >> ${UP_DIR}/code-checks.md || true
-      grep 'SCRAM error: ' ${UP_DIR}/code-checks.log | tail -12 >> ${UP_DIR}/code-checks.md || true
+      grep -A 3 ': error: \|gmake: \*\*\*' ${UP_DIR}/code-checks.log | tail -24 | sed "s|$CMSSW_BASE/src/||" >> ${UP_DIR}/code-checks.md || true
       echo '```' >> ${UP_DIR}/code-checks.md
       if ! $DRY_RUN ; then
         send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
@@ -116,22 +130,7 @@ if $CODE_FORMAT ; then
   if [ -f ${CMSSW_BASE}/src/.clang-format ] ; then
     cp ${UP_DIR}/all-changed-files.txt ${UP_DIR}/code-format-files.txt
     if [ -s ${UP_DIR}/code-format-files.txt ] ; then
-      ERR=false
-      scram build -k -j $NUM_PROC code-format USER_CODE_FORMAT_FILE="${UP_DIR}/code-format-files.txt" > ${UP_DIR}/code-format.log 2>&1 || ERR=true
-      if $ERR ; then
-        echo '-code-checks' > ${UP_DIR}/code-checks.md
-        echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/code-checks.md
-        echo -e '\nERROR: Build errors found during clang-format run.' >> ${UP_DIR}/code-checks.md
-        echo '```' >> ${UP_DIR}/code-checks.md
-        grep -A 3 ': error: \|gmake: \*\*\*' ${UP_DIR}/code-format.log | tail -12 | sed "s|$CMSSW_BASE/src/||" >> ${UP_DIR}/code-checks.md || true
-        grep 'SCRAM error: ' ${UP_DIR}/code-format.log | tail -12 >> ${UP_DIR}/code-checks.md || true
-        echo '```' >> ${UP_DIR}/code-checks.md
-        if ! $DRY_RUN ; then
-          send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
-          ${CMS_BOT_DIR}/comment-gh-pr -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/code-checks.md
-        fi
-        exit 0
-      fi
+      scram build -k -j $NUM_PROC code-format USER_CODE_FORMAT_FILE="${UP_DIR}/code-format-files.txt" > ${UP_DIR}/code-format.log 2>&1
       pushd $CMSSW_BASE/src
         git diff > ${UP_DIR}/code-format.patch
         if [ -s ${UP_DIR}/code-format.patch ] ; then
