use the correct das client i.e either das_client o dasgoclient

diff --git a/das-utils/das_client b/das-utils/das_client
--- a/das-utils/das_client
+++ b/das-utils/das_client
@@ -1,7 +1,6 @@
 #!/bin/sh
 #CMSSDT_DAS_CLIENT_SIGN:12345678901234567890ABCDEFABCDEF
 #Do not change the above magic line. It is signature for the cmssw ibs das_cleint wrapper
-
 function get_parent_cmds ()
 {
   local DEPTH=$2
@@ -16,6 +15,7 @@ function get_parent_cmds ()
   get_parent_cmds "$XPID" "$DEPTH"
 }
 
+CMD_NAME=$(basename $0)
 LIMIT_RESULTS="NO"
 QUERY=
 FORMAT="plain"
@@ -32,13 +32,13 @@ for ((i=1; i<=$#; i++)); do
 done
 
 ORIG_DAS_CLIENT=""
-for DAS_CLIENT in $(echo $PATH | tr ':' '\n' | sed 's|$|/das_client|') ; do
+for DAS_CLIENT in $(echo $PATH | tr ':' '\n' | sed "s|\$|/${CMD_NAME}|") ; do
  [ -e ${DAS_CLIENT} ] || continue
  if [ $(head -2 ${DAS_CLIENT} | grep 'CMSSDT_DAS_CLIENT_SIGN' | wc -l) -eq 0 ] ; then ORIG_DAS_CLIENT=${DAS_CLIENT}; break; fi
 done
 
 if [ "X${ORIG_DAS_CLIENT}" = "X" ] ; then
-  echo "das_client: Command not found." 1>&2
+  echo "${CMD_NAME}: Command not found." 1>&2
   exit 1
 fi
 
